### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by bobye**
1. Fix a serious annotation bug in previous commits (Thanks to Marc)
2. Use chainer accuracy() function
3. Configure some opencv parameters for label images

### CODE REVIEW

**Comment by shiba24** [comment]
@bobye Thank you for the commit!! Looks good to me. One short question: why did you comment out here? https://github.com/shiba24/deep-learning-for-human-part-discovery-in-images/pull/6/commits/d31f169f6db7f12b6551bc44eebbbfe393d645bb#diff-e44f4a60e89e820dde9bb27afa634965R113
Something wrong when training on multiple gpu / or testing? (no problem if commented out. i just would like to confirm that.)

**Comment by bobye** [comment]
I read the chainer doc. It is for multiple gpu case (my server has two
gpus).

Jianbo

**Comment by shiba24** [comment]
No, line 113 in train.py (sorry i should comment on the file directly)--
```
            #debugger.plot_result(train_mean_loss, test_mean_loss, savename='log.png')
```

**Comment by bobye** [comment]
@shiba24 I commented out this line for debugging purpose. Once  `train_mean_loss`  and  `test_mean_loss` was not in correct shape. You can keep this, I guess. They are OK.

**Comment by shiba24** [comment]
thank you! temporally i made this line in.
but please feel free to comment out anytime if you think that's better. i will merge these.

**Pull request merged**
