### PR TITLE
fix data augmentation bug in image cropping

### PR DESCRIPTION
**Pull request by bobye**
Hi, I just tried to run your code. But I found some bugs in the image augmentation part. -bob

### CODE REVIEW

**Comment by shiba24** [comment]
HI @bobye , thank you for the report and your commit! Hope you have a happy new year :)

**Comment by bobye** [comment]
Hi @shiba24 Happy new year! I am trying to reproduce the result reported in the paper, maybe we can collaborate on this  (I guess you have not yet finished the project). Do you have any particular reason to use chainer?

**Comment by shiba24** [comment]
Sure! Thank you for the suggestion. Actually there are some points (maybe you noticed) that I don't do the exact same thing as the paper.
I use chainer because I am familiar with the most, however I can use tensorflow and keras now. Do you have any framework you recommend?

**Comment by bobye** [comment]
Yes, I see that. The original paper proposed to train the refinement layers layer-by-layer, but you want an end-to-end  framework. Let's see how it works. I am still debugging some running error of your code. I will open another thread for fixing them. 

I guess we can focus on chainer now, not a big deal. But later I wish to use tensorflow for the model training part. But your current code is clear enough to make these changes later.

**Comment by shiba24** [comment]
Sure. No problem if we move to tensorflow later!

**Pull request merged**
